### ISSUE TITLE
Create initial implementation

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/QuantumCircuits.jl#1]
# Tasks
- [x] Create a state representation with either a vector or tensor
- [x] Implement single gate operations (like H or X etc)
- [x] Implement generic rotation gate operations
- [x] Implement two gate operations (i.e. CNOT)
- [x] Implement generic unit gate operations using angles
- [x] Test the circuit to build a CAT state
- [x] Test a random unitary circuit using Kronecker products and tensor dot operations.
